version: '3.8'

services:
  app:
    image: golang:1.18-alpine
    container_name: go-app
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
